FROM ubuntu:14.04

MAINTAINER schleichardt "https://github.com/schleichardt/msct-docker-containers"

RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

WORKDIR /workdir